### PR TITLE
Add in download button for importer

### PR DESCRIPTION
**Pull request by lamtu1**
Add in a way to fetch the importer file and make easy access to get the file out of import

### CODE REVIEW

**Comment by lamtu1** [comment]
fixes #2937

**Comment by straleyb** [comment]
@lamtu1 This looks good. I wonder if we need to bring in that entire controller or if it would be better if we created a hack of some kind to just open the class using class eval and then added our method in there.

I think it would be that or creating a controller that extends that one and then adds our method in.

Either would be fine on my end. The first one is probably easier. @CGillen Any input on that idea?

**Comment by lamtu1** [comment]
`DEMO:` Showing that files can be download

https://github.com/OregonDigital/OD2/assets/111306182/c8444fb6-d12e-4ff0-8417-15cdbf118bf3

**Comment by lamtu1** [comment]
> @lamtu1 This looks good. I wonder if we need to bring in that entire controller or if it would be better if we created a hack of some kind to just open the class using class eval and then added our method in there.
> 
> I think it would be that or creating a controller that extends that one and then adds our method in.
> 
> Either would be fine on my end. The first one is probably easier. @CGillen Any input on that idea?

Corey and I have a discussion on this subject, and we decided that it would be easier to approach this way for the importer by adding in a function to download. We did try to explore the other method to call the controller in other areas and seems to be a weird doozy one to do, so we end up deciding on this way as the best option for right now.

**Review by straleyb — APPROVED** [review]

**Pull request merged**
