### PR TITLE
Add in new field Local Contexts

### PR DESCRIPTION
**Pull request by lamtu1**
`FEATURE:` Create a new field of `local_contexts` into OD2.

`TASKS Part #1:` Ingest New Field
- [x] Add field `https://opaquenamespace.org/ns/localContexts` to generic_metadata field (This is include as searchable, index, allow multiple selection)
- [x] Maybe? Add this field to other areas [e.g. `video_metadata, document_metadata, image_metadata`] >> (This is `inherit` by `generic_metadata`)
- [x] Add field to `generic_metadata` to display on form in the `ORDER_TERMS` & `ORDER_PROPERTIES`
- [x] Test on searchable in `collection` and `main` search
- [x] Create a facet to sort out local context by the label (Add new facet) [from `blacklight_config`] (`search within` currently not working with new facet)

`TASKS Part #2:` Ingest in the form
- [x] Make it a controlled_properties (Double Check on it)
- [x] Create the `YML` file to host all the `id` and `term`
- [x] Create a `local_context_service` to fetch the `QAAuthority` & spec to go with it
- [x] Create a `dropdown field` in the work form & make it `multi_value` (making it not a requirement)
- [x] ~Make a `work_symbol` in form? (Setup a method for it to know where to access the variable being store)~
- [x] Making it similar to creative common field dropdown (use label page URLs for field values) 
- [x] Create an update to the generic_indexer to add this new field in tesim & ssim

`TASKS Part #3:` Display
- [x] Add in `locale` for languages
- [x] Upload icon for display
- [x] On show page, display TK and BC on below the section of the `iiif_viewer` on work show page and label icons and label title in metadata on work show page
- [x] Create Explanatory webpage for Local Contexts labels (TK/BC labels) exists in Oregon Digital [Metadata team is doing this] (~Maybe look into display it in collection if file set has it~)
- [x] Linked as appropriate from show page
- [x] Add metadata fields to MAP [Metadata team will cover this]

### CODE REVIEW

**Comment by lamtu1** [comment]
fixes #3029

**Comment by lamtu1** [comment]
`IMAGE:` Showing the temp display (may revise after feedback to change it)

Screenshot 2024-03-04 at 12 16 54 PM

**Comment by CGillen** [comment]
Is the superseded by #3126? or should this merge first then that?

**Comment by lamtu1** [comment]
@CGillen This should merge first as a hierarchy for the other PR that is depend on this PR.

**Review by CGillen — APPROVED** [review]

**Pull request merged**
