### PR TITLE
Updates view to include why sign up

### PR DESCRIPTION
**Pull request by straleyb**
Screen Shot 2022-11-23 at 10 57 19 AM

### CODE REVIEW

**Comment by CGillen** [comment]
@azle Check images above against issue #2049? Is this the direction we should go? Contact @kmthorn (if possible) about continuing to include the sidebar contents

**Comment by azle** [comment]
@CGillen and @straleyb I talked it over with Julia and we wanted to reformat the following page to be more consistent with the other login pages. I feel like the bulleted list is not necessary the user should know what they are signing up for already. If the bulleted list is needed. I prefer for it to be a tooltip using a question mark icon in the same line as the I AM AFFILIATED OR NOT AFFILIATED. Let me know if we need to talk about the changes.

This is what we would like it to look like.

 Screen Shot 2022-12-01 at 10 24 41 AM

**Comment by straleyb** [comment]
@kmthorn Are we good with moving forward in this way?

**Comment by straleyb** [comment]
@kmthorn Pinging again and adding @petersec  to help try and resolve this question about how we want to display the why sign up information or if we want to.

**Comment by petersec** [comment]
@straleyb @CGillen @azle @kmthorn @jsimic - For me, the salient text from the old bulleted list is "select, organize and share Oregon Digital materials with others." As long as that's available somewhere (or somehow) on the page, then I think we've conveyed the information that we need to the user. 

I'd be fine with the question mark and tooltip approach that Azle suggested. Perhaps the tooltip language could read: "By signing up or signing in, you will have the ability to select, organize and share Oregon Digital materials with others."

**Comment by jsimic** [comment]
Chris' wording is great!

**Comment by straleyb** [comment]
Screen Shot 2023-01-04 at 2 08 41 PM

**Comment by straleyb** [comment]
@azle I posted a screenshot of what I got set up currently. Is there anything on there that needs to be changed?

**Comment by azle** [comment]
@straleyb, can we make some adjustments with the line break for the following header "Looking to sign up..." see screen snap.

Can you also change the following text "Affiliated..." and "Not Affiliated..." to the same text as the screen snap.

Also for the links below the input forms do we need forgot password like wireframe, see screen snap.

Screen Shot 2023-01-09 at 9 33 22 AM

**Comment by straleyb** [comment]
Screen Shot 2023-01-09 at 12 02 45 PM

**Comment by straleyb** [comment]
@azle I got it updated. Let me know if there is anything else that needs updated

**Comment by azle** [comment]
@straleyb, looks great! Thank you!

**Review by CGillen — APPROVED** [review]

**Pull request merged**
