### PR TITLE
Add in favicon into OD2

### PR DESCRIPTION
**Pull request by lamtu1**
Input a `favicon` into `OD2` to make it distinguish rather than a default favicon.

### CODE REVIEW

**Comment by lamtu1** [comment]
`Fix Issue:`  #403

**Comment by azle** [comment]
@lamtu1  Here is an updated favicon with a transparent background.

[favicon_io.zip](https://github.com/OregonDigital/OD2/files/12304972/favicon_io.zip)

**Comment by lamtu1** [comment]
@azle Here is new imaging to the favicon

`Light Ver`

Screenshot 2023-08-09 at 10 46 37 AM

`Dark Ver`

Screenshot 2023-08-09 at 10 45 53 AM

**Review by CGillen — APPROVED** [review]

**Comment by azle** [comment]
@lamtu1 Fantastic, this looks great! Its ready to go!

**Pull request merged**
