### PR TITLE
Remove unnecessary text from under 'Public' visibility option

### LINKED ISSUE #3011: Remove unneeded text from Edit Form Visiblity box
### Descriptive summary

On the Edit Form, in the Visibility selection box, remove the display of text under the 'Public' option, starting with `Please note, making`

image

This isn't relevant for Oregon Digital, and removing it will free up vertical space in the right sidebar.

### Expected behavior

In the Visibility box, the text under 'Public' option only needs to read 'Make available to all.'

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

### PR DESCRIPTION
**Pull request by megwalt**
closes #3011 
Remove unnecessary text from under 'Public' visibility option when the radio button is selected.

Screenshot:
Public visibility option selected

### CODE REVIEW

**Review by CGillen — APPROVED** [review]
Looks good. Those integration tests have started becoming pretty flaky lately. I restarted them to see if it helps, otherwise I can work with you on figuring out what is going on with them if you would like

**Comment by CGillen** [comment]
Ah, it's these:
https://github.com/OregonDigital/OD2/blob/master/spec/system/create_audio_spec.rb#L65
You can just change those to something else in the sidebar. like: `Make available to all.`

**Comment by megwalt** [comment]
It seems that line was checking to see if the public option was selected. The 'Make available to all.' is always in the sidebar. Should I try to get an equivalent check to see if the public option has been selected in there instead?

**Comment by megwalt** [comment]
> It seems that line was checking to see if the public option was selected. The 'Make available to all.' is always in the sidebar. Should I try to get an equivalent check to see if the public option has been selected in there instead?

On second thought, that line was probably checking to make sure that the text showed after the public option was selected, not that the option was successfully selected. I'll edit the text that's being checked.

**Comment by CGillen** [comment]
> > It seems that line was checking to see if the public option was selected. The 'Make available to all.' is always in the sidebar. Should I try to get an equivalent check to see if the public option has been selected in there instead?
> 
> On second thought, that line was probably checking to make sure that the text showed after the public option was selected, not that the option was successfully selected. I'll edit the text that's being checked.

Yeah, I think you're right, it's just for checking to see if it pops up if public gets selected. I'm not too worried about that check

**Pull request merged**
