### PR TITLE
task to set geonames uris to https

### PR DESCRIPTION
**Pull request by luisgreg99**
fixes https://github.com/OregonDigital/OD2/issues/963
this task covers the case mentioned in https://github.com/OregonDigital/OD2/issues/943#issuecomment-577836324

### CODE REVIEW

**Comment by straleyb** [comment]
It might be a good idea to extract this code into a service and then test its functionality there.

**Comment by lsat12357** [comment]
Is this more of a remediation task rather than something that needs to go into the repo?

**Comment by straleyb** [comment]
Even if its a remediation task I still think it should go somewhere. If we end up creating 1 new task per remediation, then we could end up with several tasks lying around for unnecessary reasons. Id imagine if the idea is a one off remediation task, then I think it should exist as a script instead of a rake task. But I still think testing it is necessary.

**Comment by luisgreg99** [comment]
It's actually a one time script to fix a specific case (only for seed data) in location field that resulted from a bug already fixed, so I think we can close this one.

**Pull request closed without merging**
