### PR TITLE
Add link to thumbnail collection

### PR DESCRIPTION
**Pull request by lamtu1**
Create a way to add link to collection with the thumbnail for collection.

### CODE REVIEW

**Comment by lamtu1** [comment]
fixes #2950

**Comment by lamtu1** [comment]
closes #2950

**Comment by lamtu1** [comment]
fixes #2950

**Comment by lamtu1** [comment]
`DEMO` - Showing the clickable thumbnail of Collection.

https://github.com/OregonDigital/OD2/assets/111306182/6c033ce7-f982-41ab-bd0b-4de802578662

**Review by CGillen — CHANGES_REQUESTED** [review]
Now that it's a link, can the alt text be the title of the collection like the thumbnails for works?

**Review by CGillen — APPROVED** [review]

**Pull request merged**
